In [198]:
from bs4 import BeautifulSoup as bs4
import requests
import pandas as pd

pages=[]
prices=[]
stars=[]
titles=[]
urlss=[]

# I used this website for this project: http://books.toscrape.com

In [199]:
# This code is just to increment the page

pages_to_scrape=5

for i in range(1,pages_to_scrape+1):
    url = ('http://books.toscrape.com/catalogue/page-{}.html').format(i)
    pages.append(url)
#print(pages)

# This code is just parsing text

for item in pages:
    page = requests.get(item)
    soup = bs4(page.text, 'html.parser')
    #print(soup.prettify())
        
## This code is to get the book titles 
    
    for i in soup.findAll('h3'):
        ttl=i.getText()
        #print(ttl)
        titles.append(ttl)
    
## This code is to get the book price
    
    for j in soup.findAll('p', class_='price_color'):
        price=j.getText()
        prices.append(price)

## This code is to get the star rating

    for s in soup.findAll('p', class_='star-rating'):
        for k,v in s.attrs.items():
            star =v[1]
            stars.append(star) 

## This code is to get the book image URL 

    divs =soup.findAll('div', class_='image_container')
    for thumbs in divs:
        tgs=thumbs.find('img',class_='thumbnail')
        urls='http://books.toscrape.com/'+str(tgs['src'])
        newurls=urls.replace("../","")
        urlss.append(newurls)

In [200]:
data={'Title': titles, 'Prices': prices, 'Stars':stars, "URLs":urlss}
#data

In [201]:
df=pd.DataFrame(data=data)
df.index+=1

In [202]:
df

,Title,Prices,Stars,URLs
1,A Light in the ...,Â£51.77,Three,http://books.toscrape.com/media/cache/2c/da/2c...
2,Tipping the Velvet,Â£53.74,One,http://books.toscrape.com/media/cache/26/0c/26...
3,Soumission,Â£50.10,One,http://books.toscrape.com/media/cache/3e/ef/3e...
4,Sharp Objects,Â£47.82,Four,http://books.toscrape.com/media/cache/32/51/32...
5,Sapiens: A Brief History ...,Â£54.23,Five,http://books.toscrape.com/media/cache/be/a5/be...
...,...,...,...,...
96,Lumberjanes Vol. 3: A ...,Â£19.92,Two,http://books.toscrape.com/media/cache/5f/b1/5f...
97,"Layered: Baking, Building, and ...",Â£40.11,One,http://books.toscrape.com/media/cache/98/d1/98...
98,Judo: Seven Steps to ...,Â£53.90,Two,http://books.toscrape.com/media/cache/5f/52/5f...
99,Join,Â£35.67,Five,http://books.toscrape.com/media/cache/93/63/93...
100,In the Country We ...,Â£22.00,Four,http://books.toscrape.com/media/cache/fe/ea/fe...

In [186]:
df.to_excel("C:/Users/ITEK/OneDrive/DATASET/Web Scraping/Books to Scrape.xlsx")